### DISCUSSION TITLE
How to use this with Mimir?

### DISCUSSION THREAD

**Discussion by alexandrospanayi** [cloudflare/pint#1127] [Q&A]
Hey folks. 

Just found out about this great tool. Wanted to start playing around with it however curious to know how this would work with Mimir instead of a local prom instance. 

I've tried various configs but pint is returning various 404s.

**Comment by loganjohnson-wk** [comment]
Seems like they don't plan on supporting Mimir according to this [issue](https://github.com/cloudflare/pint/issues/755) which is a real bummer, would be super nice.

I did try setting up a remote read similar to what that issue mentioned and I _think_ it's working? I'll leave my steps below but it's by no means optimal so this is probably where I'll stop. Would be interested if there was a better way...

### Remote read setup

To start, the setup I was testing was using a Mimir instance running in a k8s cluster so there is some clunkiness with port forwarding and it might be better to hit it directly.

#### Gather the rules
First had to grab the rules from the Mimir ruler since there is no remote read for rules. Used the `/ruler/rule_groups` endpoint, [docs](https://grafana.com/docs/mimir/latest/references/http-api/#ruler-rules), which gives all the rules so have to filter down to the ones I wanted with [yq](https://github.com/mikefarah/yq).

``` bash
> kubectl port-forward svc/mimir-ruler 13498:8080
# Get the rules for `my-tenant` and format them as prometheus rules
> curl 'http://localhost:13498/ruler/rule_groups' | yq '.my-tenant.[] | {"groups": .}' > my-tenant-rules.yaml
```

I wanted to use the `prometheus/api/v1/rules?type=record` endpoint, [docs](https://grafana.com/docs/mimir/latest/references/http-api/#list-prometheus-rules), but running prometheus locally with those rules didn't work with that output format. Seems like that is what `pint` could query though.

#### Run Prometheus locally

With the rules then we just need to run prometheus locally with the following config and pointing to the mimir-gateway...

``` bash
> kubectl port-forward svc/mimir-gateway 8888:80
> prometheus --config.file=remote-prometheus-config.yaml
```

<details>
<summary>remote-prometheus-config.yaml</summary>

``` yaml
remote_read:
  - url: http://localhost:8888/prometheus/api/v1/read
    name: mimir
    headers:
      X-Scope-OrgID: my-tenant

rule_files:
  - my-tenant-rules.yaml

# Scrape itself so it can expose the `prometheus_build_info` metric
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
```

</details>

#### Run pint

With all that then can run `pint`. I was interested in the watch mode but I'm sure you could run the check directly with the rules file instead, in fact that would probably be better so the rules aren't recalculated locally 🤷 

``` bash
> pint watch rule_files testing
```

<details>
<summary>.pint.hcl</summary>

``` hcl
prometheus "testing" {
  uri      = "http://localhost:9090"
  uptime   = "prometheus_build_info"
}
```

</details>

I will say my port-forwarding was not having a good time so the pint metrics weren't the best indicator of what was working or not. Might work better if it's running in the cluster 🤔
