### DISCUSSION TITLE
pint for PrometheusRule CRD

### DISCUSSION THREAD

**Discussion by tabrizu891** [cloudflare/pint#298] [Q&A] [answered]
Is there any way to check rules against PrometheusRule CRD yamls?
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts-ingress
  namespace: monitoring
spec:
  groups:
  - name: ingress
    rules:
      - alert: IngressDown
        expr: up{namespace="ingress-nginx"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Ingress down
          description: "Ingress instance is down."
```
