### ISSUE TITLE
GitLab integration - report not being attached to MR

### ISSUE THREAD

**Issue by metheu** [cloudflare/pint#1038]
Hi! We are in the process of adding pint (which is awesome by the way!) to our CI so we can provide quick feedback to our devs when adding rules. I have integrated pint and it seems like it's either failing silently or there is wrong configuration on my end. Can someone help me debug this?

This is the gitlab CI:

```
variables:
  PINT_VERSION: 0.62.2

.pint-ci:
  stage: lint
  image: ghcr.io/cloudflare/pint:$PINT_VERSION
  interruptible: true
  rules:
    - exists:
        - .pint.hcl
  variables:
    DEFAULT_WORKSPACE: "$CI_PROJECT_DIR"
    DEFAULT_BRANCH: "$CI_DEFAULT_BRANCH"
    GITLAB_AUTH_TOKEN: $PERSONAL_TOKEN
    GITHUB_PULL_REQUEST_NUMBER: $CI_MERGE_REQUEST_IID
  before_script:
    - git fetch origin $MAIN_BRANCH
    - git checkout $MAIN_BRANCH
    - git checkout -
  script:
    - pint -l $PINT_LOG_LEVEL ci
  tags:
    - eks-runner

```

Below is the CI log: 
```
common/components/rules/main/test-rule-rules.yaml:13-19 Bug: `team` label is required. (rule/label)
 13 |         - alert: test-rule
 14 |           expr: vector(1)
 15 |           for: 5m
 16 |           labels:
 17 |             # severity: critical
 18 |             # team: platform
 19 |           annotations:
common/components/rules/main/test-rule-rules.yaml:14 Warning: Alert query doesn't have any condition, it will always fire if the metric exists. (alerts/comparison)
 14 |           expr: vector(1)
level=DEBUG msg="Getting current GitLab user details"
level=DEBUG msg="performing request" reporter=GitLab method=GET url=https://gitlab.com/api/v4/user
level=DEBUG msg="Finding merge requests for current branch" branch=HEAD
level=DEBUG msg="performing request" reporter=GitLab method=GET url=https://gitlab.com/api/v4/projects/37813876/merge_requests?page=1&source_branch=HEAD&state=opened
level=DEBUG msg="Stopping query workers" name=prod-main uri=https://prometheus-main.prod.appfollow.io/
level=DEBUG msg="Stopping query workers" name=prod-etl uri=https://prometheus-etl.prod.appfollow.io/
level=ERROR msg="Execution completed with error(s)" err="problems found"
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: command terminated with exit code 1
```

It seems like it makes a request to `/projects` and it stops there. Any thoughts?
