### ISSUE TITLE
relaxed mode no longer parses rule groups with top-level YAML lists

### ISSUE THREAD

**Issue by DubrovskyEI** [cloudflare/pint#1405]
Hello!

Use pint `0.73.0`  and `relaxed` parser no longer detects alerting/recording rules defined under top-level YAML lists like this:

```
- name: cassandra-basic
  rules:
  - alert: CassandraNodeDown
    expr: ((sum without (instance_ip) (up{instance!~"(cassin|cassam).*",job="cassandra"} UNLESS ON(instance) cassandra_stats{instance!~"(cassin|cassam).*",name=~"java:lang:memory:.+:max"}) <= bool 0))
    for: 5m
    labels:
      severity: critical
      alertType: application
```
This format worked correctly in previous versions like `v0.65.1` and `v0.70.0`, where `relaxed` mode would recursively walk the YAML tree and extract rules from arbitrary custom structures, as described in the documentation.

## Expected Behavior (based on documentation)

Per the [pint parser documentation](https://cloudflare.github.io/pint/#yaml-parser):

> “Relaxed” parser mode will load anything that can be parsed as Prometheus rule, while “strict” parser mode will fail if it reads a file that wouldn’t load cleanly as Prometheus config file

But starting from `0.72.0` it is not.

### Broken in 0.72.0

```
cat test.yml 
- name: cassandra-basic
  rules:
  - alert: CassandraNodeDown
    expr: ((sum without (instance_ip) (up{instance!~"(cassin|cassam).*",job="cassandra"} UNLESS ON(instance) cassandra_stats{instance!~"(cassin|cassam).*",name=~"java:lang:memory:.+:max"}) <= bool 0))
    for: 5m
    labels:
      severity: critical
      alertType: application
```

```
pint version
0.73.0 (revision: fe1305aff10a8c1819689a1e2a64294f4d5c6fe2)
```

```
cat pint.hcl
// Do not require 'groups -> rules -> rule' structure
parser {
  relaxed = [".*"]
}

// Due to incompability with VictoriaMetrics
checks {
  disabled = ["promql/syntax"]
}
```

```
pint -c pint.hcl lint test.yml
level=INFO msg="Loading configuration file" path=pint.hcl
level=INFO msg="Finding all rules to check" paths=["test.yml"]
level=INFO msg="Checking Prometheus rules" entries=0 workers=10 online=true
level=INFO msg="No rules found, skipping Prometheus discovery"
```

### Works with 'flat' YAML structure

```
cat test_1.yml
  - alert: CassandraNodeDown
    expr: ((sum without (instance_ip) (up{instance!~"(cassin|cassam).*",job="cassandra"} UNLESS ON(instance) cassandra_stats{instance!~"(cassin|cassam).*",name=~"java:lang:memory:.+:max"}) <= bool 0))
    for: 5m
    labels:
      severity: critical
      alertType: application
```

```
pint -c pint.hcl lint test_1.yml
level=INFO msg="Loading configuration file" path=pint.hcl
level=INFO msg="Finding all rules to check" paths=["test_1.yml"]
level=INFO msg="Checking Prometheus rules" entries=1 workers=10 online=true
Warning: smelly regexp selector (promql/regexp)
  ---> test_1.yml:2 -> `CassandraNodeDown`
2 |     expr: ((sum without (instance_ip) (up{instance!~"(cassin|cassam).*",job="cassandra"} UNLESS ON(instance) cassandra_stats{instance!~"(cassin|cassam).*",name=~"java:lang:memory:.+:max"}) <= bool 0))
                                                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `{name=~"java:lang:memory:.+:max"}` looks like a smelly selector that tries to extract substrings from the value, please consider breaking down the value of this label into multiple smaller labels

level=INFO msg="Problems found" Warning=1
```

## Works in 0.71.8

```
./pint-0.71.8 version
0.71.8 (revision: c08271baa72e9531c5c7728a70c18f5ce0b07147)
```

```
./pint-0.71.8 -c pint.hcl lint test.yml
level=INFO msg="Loading configuration file" path=pint.hcl
level=INFO msg="Finding all rules to check" paths=["test.yml"]
level=INFO msg="Checking Prometheus rules" entries=1 workers=10 online=true
Warning: smelly regexp selector (promql/regexp)
  ---> test.yml:4 -> `CassandraNodeDown`
4 |     expr: ((sum without (instance_ip) (up{instance!~"(cassin|cassam).*",job="cassandra"} UNLESS ON(instance) cassandra_stats{instance!~"(cassin|cassam).*",name=~"java:lang:memory:.+:max"}) <= bool 0))
                                                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `{name=~"java:lang:memory:.+:max"}` looks like a smelly selector that tries to extract substrings from the value, please consider breaking down the value of this label into multiple smaller labels

level=INFO msg="Problems found" Warning=1
```

Could you please clarify whether this is a configuration issue or a changed behavior introduced in version `0.72.0`?
