### ISSUE TITLE
Using yaml anchors results in false positives e.g yaml/parse

### ISSUE THREAD

**Issue by filippog** [cloudflare/pint#257]
Hi @prymitive !
Thank you for pint, it looks really good!

We (SRE at Wikimedia Foundation) are evaluating it for our Prometheus alerts currently and ran into a potential issue around YAML anchors.

Consider the following:

```
groups:
- name: certmanager
  rules:
  - &CertManagerCertExpirySoon
    alert: CertManagerCertExpirySoon
    expr: certmanager_certificate_expiration_timestamp_seconds - time() < (9 * 24 * 3600)
    for: 5m
    labels:
      team: sre
      severity: warning
    annotations:
      summary: "Certificate {{ $labels.namespace }}/{{ $labels.name }} in is about to expire"
      description: "The certificate {{ $labels.name }} in namespace {{ $labels.namespace }} is {{ $value | humanizeDuration }} from expiry. It should have been refreshed 9 days before expiry"
      runbook: https://wikitech.wikimedia.org/wiki/Kubernetes/cert-manager
  - <<: *CertManagerCertExpirySoon
    expr: certmanager_certificate_expiration_timestamp_seconds - time() < (7 * 24 * 3600)
    labels:
      team: sre
      severity: critical
```

Running `pint lint` will result in a `yaml/parse` error:

```
incomplete rule, no alert or record key (yaml/parse)                                                                                                                               
||     expr: certmanager_certificate_expiration_timestamp_seconds - time() < (7 * 24 * 3600)
```

Even though the alert does have `alert` clause after resolving anchors. What do you think ?
