### ISSUE TITLE
Lost support for linting rules organized into PrometheusRule files

### ISSUE THREAD

**Issue by davidpellcb** [cloudflare/pint#460]
My team deploys the Prometheus stack on Kubernetes and uses the Prometheus Operator and its `PrometheusRule` CRD for managing rules. All of our rules are organized into `PrometheusRule` files. Example:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alertmanager
spec:
  groups:
  - name: Alertmanager
    rules:
    - alert: Alertmanager failed to reload config
       ... etc ...
```

I first started looking at Pint earlier this year around version 18. In that version, Pint is able to parse the rules out of these files. I just recently came back to actually implementing Pint in our project this week, though, and it seems that a file with this structure is no longer supported:

```
level=error msg="Failed to unmarshal file content" error="yaml: unmarshal errors:\n  line 1: field apiVersion not found in type rulefmt.RuleGroups\n  line 2: field kind not found in type rulefmt.RuleGroups\n  line 3: field metadata not found in type rulefmt.RuleGroups\n  line 5: field spec not found in type rulefmt.RuleGroups" lines=1-66 path=rules/grafana.yaml
```

```
rules/grafana.yaml:1: field apiVersion not found in type rulefmt.RuleGroups (yaml/parse)
 1 | apiVersion: monitoring.coreos.com/v1
```

Do you happen to know when this support was removed, and is there possibly any built-in support or config tricks I could use to use the more recent versions without having to change how we organize our rules?
