### ISSUE TITLE
Bug: pint reports false-positive `template is using "xxx" label but the query removes`

### ISSUE THREAD

**Issue by d-mankowski-synerise** [cloudflare/pint#681]
We have alert defined like this:

```yaml
        - alert: ScyllaNonBalancedcqlTraffic
          expr: >
            abs(rate(scylla_cql_updates{conditional="no"}[1m]) - scalar(avg(rate(scylla_cql_updates{conditional="no"}[1m]))))
            /
            scalar(stddev(rate(scylla_cql_updates{conditional="no"}[1m])) + 100) > 2
          for: 10s
          labels:
            advisor: balanced
            dashboard: cql
            severity: moderate
            status: "1"
            team: team_devops
          annotations:
            description: CQL queries are not balanced among shards {{ $labels.instance }} shard {{ $labels.shard }}
            summary: CQL queries are not balanced
```

And pint reports the following problem:

```text
infrastructure/base/mimir/rules/synerise/scylla_alerts.yaml:91-103 Bug: template is using "instance" label but the query removes it (alerts/template)
  91 |           expr: >
  92 |             abs(rate(scylla_cql_updates{conditional="no"}[1m]) - scalar(avg(rate(scylla_cql_updates{conditional="no"}[1m]))))
  93 |             /
  94 |             scalar(stddev(rate(scylla_cql_updates{conditional="no"}[1m])) + 100) > 2
 ...
 103 |             description: CQL queries are not balanced among shards {{ $labels.instance }} shard {{ $labels.shard }}
infrastructure/base/mimir/rules/synerise/scylla_alerts.yaml:91-103 Bug: template is using "shard" label but the query removes it (alerts/template)
  91 |           expr: >
  92 |             abs(rate(scylla_cql_updates{conditional="no"}[1m]) - scalar(avg(rate(scylla_cql_updates{conditional="no"}[1m]))))
  93 |             /
  94 |             scalar(stddev(rate(scylla_cql_updates{conditional="no"}[1m])) + 100) > 2
 ...
 103 |             description: CQL queries are not balanced among shards {{ $labels.instance }} shard {{ $labels.shard }}
```

And yet, the query does not remove the labels:
<img width="1293" alt="image" src="https://github.com/cloudflare/pint/assets/101267779/bcca9483-1dd2-47e9-9d4d-0fbd6ea89018">
