### ISSUE TITLE
Template rule firing on absent when not `=` matching

### ISSUE THREAD

**Issue by bnordbo** [cloudflare/pint#706]
The following passes `pint lint` (version 0.45.0) just fine:

```yaml
groups:
- name: test
  rules:
  - alert: Test
    expr: absent(test_total{foo="bar"})
    annotations:
      summary: "{{ $labels.foo}}"
```

Changing the matcher to `!=` seems to make sense:

```yaml
groups:
- name: test
  rules:
  - alert: Test
    expr: absent(test_total{foo!="bar"})
    annotations:
      summary: "{{ $labels.foo}}"
```

However this is flagged as a problem by pint:

```
$ pint lint /mnt/boo.yaml
/mnt/boo.yaml:5-7: template is using "foo" label but absent() is not passing it (alerts/template)
 5 |     expr: absent(test_total{foo!="bar"})
 .
 7 |       summary: "{{ $labels.foo}}"

level=info msg="Problems found" Bug=1
level=fatal msg="Execution completed with error(s)" error="problems found"
```

The same goes for matchers using `=~` and `!~`.

Note that it requires the following three components in order to trigger:

- An expression using `absent`.
- That expression using a label matcher that is not `=`.
- That label being used in the rule template.

Is this an error in pint, or an odd quirk related to `absent`?
