### ISSUE TITLE
Add support for Prometheus Operator crd rules

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [cloudflare/pint#876]
# context
We want to setup a linting pipline and currently have to work around the fact that we use prometheus operator CRDs.
Which are almost the same are rules but we have to unwrap the rules using yq:
```bash
yq .spec rule.yaml > raw-rules/rule.yaml
pint lint raw-rules/rule.yaml
```

It would be handy to add support for the operator CRDs which lints the spec field in case the CRD has a kind name `PrometheusRule`.
so then you could do `pint lint rule-crd.yaml` 

I don't mind adding a PR to contribute this feature.

**Comment by prymitive** [comment]
> We want to setup a linting pipline and currently have to work around the fact that we use prometheus operator CRDs.
>  Which are almost the same are rules but we have to unwrap the rules using yq

Can you please give some details what that actually means? Why do you need to "unwrap" them? What does this "unwrapping" do? Why doesn't pint work without it? Are you getting errors? What kind of errors? This ticket assumes that everyone knows what "CRDs" are, unfortunately I don't.

**Comment by boris-smidt-klarrio** [comment]
Ah sorry,

A CRD is a custom resource definition which extends the api of a kubernetes cluster.
There is a commonly used operator an application which reads prometheus CRD's and applies them to the Prometheus application running in Kubernetes.

For example this is a small CRD for the prometheus controller.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus-selector-target: system-prometheus
  name: my rule
  namespace: monitoring
spec:
# from this point on we actually have something pint can lint
  groups:
    - name: my-alert
      rules:
		- alert: ContainerBuilderError
```

So if the pint could work directly with the CRD then we would immediacy know the correct line which caused the error.
As an alternative adding a field selector so we could tell pint the rules are in 'spec' or another yaml field  then pint could also report the correct line number containing the error without needing to maintain the CRD compatibility.

source:
https://github.com/prometheus-operator/prometheus-operator

So my current workaround is to yq to extract the rules form the CRD but then the error of pint don't match the line of the CRD file.
